trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and Push Docker image
  inputs:
    containerRegistry: 'dockerhub-service-connection'
    repository: 'kfranco021/unyleya_projeto'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
