trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and Push Docker image
  inputs:
    containerRegistry: 'DockerHubServiceConnection3.0'
    repository: 'seuusuario/unyleya_projeto_cicd_kfranco021'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
